#!/usr/bin/env perl

use v5.10;
use strict;
use warnings;

use LWP::Simple;

use Data::Dumper;
use Date::Calc qw/Decode_Date_US/;

my $page = get "http://bluray.highdefdigest.com/releasedates.html";
die "Server busy\n" unless $page;

my @lines = split /^/, $page;
my $date;
for (@lines) {
    if (/<em class="date">(.*?)<\/em>/) {
        my ($y,$m,$d) = Decode_Date_US($1);
        $date = sprintf "%d-%02d-%02d", $y,$m,$d;
    }
    if ($date and (/<span>(.*?)<\/span>/ or m,<a href=".*?">(.*?)</a>,)) {
        say "$date $1";
    }
        
    last if /Release Dates (Postponed|Pending)/;
}
