#!/usr/bin/env perl

use strict;
use warnings;

my $less = "less";

$less = "cdiff -c always | less -R" if -x "/usr/local/bin/cdiff";

my $file = shift;

die "Usage: $0 file\n" unless $file and -r $file;

my @commits = map { chomp; s/commit //; $_ } grep /^commit /, `git log $file`;

for (@commits) {
    system "git show $_ $file | $less";
}
