#!/usr/bin/env perl
use strict;
use warnings;

my $total = 0;
sub seconds {
    my $s = shift;
    my $seconds = 0;
    my $mult = 1;
    while ($s =~ s/:?(\d+)$//) {
        $seconds += $1 * $mult;
        $mult *= 60;
    }
    $seconds;
}
sub string {
    my $s = shift;
    my $h = int($s / 3600);
    $s -= $h * 3600;
    my $m = int($s / 60);
    $s -= $m * 60;
    sprintf "%02d:%02d:%02d", $h, $m, $s;
}

for (sort @ARGV) {
    my $o = `ffmpeg -i "$_" 2>&1`;
    my $l = "";
    if ($o =~ /Duration: ([\d:]+)/) {
        $l = $1;
        $total += seconds($l);
    }
    print "$_: $l\n";
}
print "total: ",string($total),"\n";
