#!/usr/bin/env perl
use v5.10;
use strict;
use warnings;

my %seen = (from => 1);
sub unrar {
	my $file = shift;
	my $unrar = `unrar x -o+ '$file' 2>&1`;
	while ($unrar =~ /^Extracting\s*(\S+)/mg) {
		next if $seen{$1}++;
		say $1;
	}
	if ($? >> 8) {
		say "\terror: $unrar";
	}
}

foreach my $file (@ARGV) {
	if (-d $file) {
		my @rar = `find '$file' -type f -name '*.rar' 2>/dev/null`;
		my @mkv = `find '$file' -type f -name '*.mkv' 2>/dev/null`;
		foreach my $rar (@rar) {
			next if $rar =~ m,\bSample\b,;
			chomp $rar;
			unrar $rar;
		}
		foreach my $mkv (@mkv) {
			next if $mkv =~ m,\bSample\b,;
			chomp $mkv;
			my $f = $mkv;
			$f =~ s/.*\///;
			my $cp = `cp '$mkv' . 2>&1`;
			say $f;
			if ($? >> 8) {
				say "\terror: $cp";
			}
		}
	}
	else {
		unrar $file;
	}
}
