#!/usr/bin/env perl
use strict;
use warnings;

for (sort @ARGV) {
    my $o = `ffmpeg -i "$_" 2>&1`;
    my $l = "";
    print "$_:\n";
    while ($o =~ /(Stream.*?(Audio|Subtitle):.*)/g) {
        print "\t$1\n";
    }
}
