#!/bin/sh
today=`/bin/date +%F-%H%M%S`

sudo tarsnap -c -f laptop-important-$today faktura .emacs .ssh projects /mnt/lbr/financial .password MOR ANETTE TIMER

#sudo tarsnap --list-archives | sort
#xargs -n 1 sudo tarsnap -d -f
